export const READINGS: string[] = [
    'Lectura en voz alta',
    'El jardín esté lleno de suspiros',
    'Tláloc',
    'México-Tenochtitlan',
    'Lluvia oblicua',
    'La Mosca que soñaba que era un Águila',
    'Un son para niños antillanos',
    'Paco Yunque',
    'Altazor',
    'La Salvaje',
    'La niña y le estrella',
    'El español',
    'El perro y un pedazo de carne',
    'Un viaje en tren',
    'Vagabundo',
    'Cómo llamar a un gato',
    'Moby Dick',
    'Desde esta luz',
    'La llovizna de abril',
    'La opinión de los demás',
    'La infancia de Cuauhtémoc',
    'Yo escucho los cantos',
    'Una familia de árboles',
    'Tsaá chaakú iniyu',
    'Árbol',
    'La Lula',
    'Carrusel',
    'Pera verde',
    'Orfeo y Eurídice',
    'El aeroplano',
    'Diccionario poético 1',
    'Canto florido',
    'Los trompos y su espiral',
    'La formación del mundo',
    'Falsa domesticación',
    'En Hornos',
    'Axolotl',
    'Diccionario poético 2',
    'Soy una gaviota',
    'Asombro',
    'El Gólem',
    'Poesía visual',
    'Canciones del sinsentido',
    'Ár ‘rini ar de:thä pa ya ja ja’i',
    'El origen del maíz para los humanos',
    'El león y la liebre',
    'Seda de araña',
    'Veinte mil leguas de viaje submarino',
    'Equilibrista',
    'Cadidi ca bigu',
    'Las tortugas',
    'Relaciones y cartas',
    'El Quelite',
    'La lechera',
    'El fénix',
    'Drácula',
    'Los pájaros',
    'Diccionario poético 3',
    'Visión de Anáhuac',
    'La orilla del mar',
    'Ecología',
    'El traje nuevo del emperador',
    'Aire',
    'Negro cuento de la mujer blanca',
    'La tempestad',
    'Volcanes',
    'Robinson Crusoe',
    'Yo en el fondo del mar',
    'Gatos ilustres',
    'Ulises vence a Polifemo',
    'Gonzalo Guerrero',
    'Lavanderas del Grijalva'
];